* GEOMM

A simple no-nonsense library for computing common geometry on
macromolecular systems.

This library aims to work completely on numpy arrays and knows nothing
about molecule or system topologies, atom types, or other "real world"
properties.

You only need to provide atom coordinates, atom indices (for molecule,
group, molecule selections etc.), and other parameters for functions.

Thus it aims to be more like numpy or scipy itself than a typical
macromolecular software library, except that the particular routines
and functions are usually found in that context.

** Installation

To install geomm make sure you have cython installed then:
#+BEGIN_SRC bash
git clone https://github.com/ADicksonLab/geomm.git
cd geomm

# compile the cython modules
python setup.py build_ext --inplace
# install it
pip install -e .

#+END_SRC

** Community

Discussion takes place on riot.im (#geomm:matrix.org) which is a slack-like app that works
on the Matrix protocol:
[[https://riot.im/app/#/room/#geomm:matrix.org]]


You can also contact me directly:

samuel.lotz@salotz.info
