* geomm

Current [[https://zenodo.org/badge/latestdoi/125404701][Zenodo DOI]].

# badges

#+begin_export html
<a href="https://zenodo.org/badge/latestdoi/125404701"><img src="https://zenodo.org/badge/125404701.svg" alt="DOI"></a>
#+end_export

# end badges

A simple no-nonsense library for computing common geometry on
macromolecular systems.

This library aims to work completely on numpy arrays and knows nothing
about molecule or system topologies, atom types, or other "real world"
properties.

You only need to provide atom coordinates, atom indices (for molecule,
group, molecule selections etc.), and other parameters for functions.

Thus it aims to be more like numpy or scipy itself than a typical
macromolecular software library, except that the particular routines
and functions are usually found in that context.


** Docs and Info

See the [[file:./info][info]] directory for the documentation and history of the
project. The [[file:./info/README.org][README]] serves as an index. These files are (mostly) in
emacs org-mode and serve as the primary source of documentation. 

Other "rendered" versions may exist and be published. The default
location is at
[[https://salotz.github.io/geomm][adicksonlab.github.io/geomm]]
in HTML rendered with Sphinx.

** COMMENT Maintenance Intent

** Developing

See the [[file:sphinx/source/dev_guide.org][Developers Guide]] for developing.
