* GEOMM

A simple no-nonsense library for computing common geometry on
macromolecular systems.

This library aims to work completely on numpy arrays and knows nothing
about molecule or system topologies, atom types, or other "real world"
properties.

You only need to provide atom coordinates, atom indices (for molecule,
group, molecule selections etc.), and other parameters for functions.

Thus it aims to be more like numpy or scipy itself than a typical
macromolecular software library, except that the particular routines
and functions are usually found in that context.

** Installation

Get it from PyPI:

#+BEGIN_SRC bash
  pip install geomm
#+END_SRC

Or you can get the latest:

#+BEGIN_SRC bash

git clone https://github.com/ADicksonLab/geomm.git
cd geomm

# you need cython to compile
pip install cython

# install it
pip install -e .

#+END_SRC


** Community

Discussion takes place on riot.im (#geomm:matrix.org) which is a slack-like app that works
on the Matrix protocol:
[[https://riot.im/app/#/room/#geomm:matrix.org]]


You can also contact me directly:

samuel.lotz@salotz.info

* Developing

** Building Docs

Install these packages:

#+BEGIN_SRC bash
pip install sphinx guzzle_sphinx_theme sphinxcontrib-napoleon nbsphinx
#+END_SRC

Install pandoc for converting org-mode files to rst (optional).

You can follow the instructions on the site or just use anaconda:

#+BEGIN_SRC bash
conda install pandoc
#+END_SRC

Then run the build script. This uses the make file and additionally
runs api-doc, and converts org-mode source files to rst using pandoc.

#+BEGIN_SRC bash
cd sphinx
chmod u+x build.sh
./build.sh
#+END_SRC


To run the current deployments of the docs run the deploy script:

#+BEGIN_SRC bash
chmod u+x deploy.sh
./deploy.sh
#+END_SRC
