package:
  name: geomm
  version: 0.1.7

source:
  fn: geomm-0.1.7.tar.gz
  url: htt/{{ version }}/{{ name }}-{{ version }}.tar.gz
  # TODO: way to specify a hole or 
  sha256:

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  entry_points:
    - geomm = geomm.cli:cli

requirements:
  build:
    - python
    - setuptools
    - wheel

  host:
    - python
    
  run:
    - python
    

about:
  home: https://github.com/ADicksonLab/geomm
  license: MIT
  license_file: LICENSE
  summary: "A simple no-nonsense library for computing common geometry on macromolecular systems."
  doc_url: https://geomm.github.io/geomm
  dev_url: https://github.com/ADicksonLab/geomm

extra:
  recipe-maintainers:
    - salotz
